version: '3'
services:
  mongo-db:
    image: mongo:3.2.4
    container_name: "mongo-db"
    ports:
      - 27017:27017
  app:
    build: .
    image: edilson/scheduler-management
    ports:
      - "8080:8080"
    links:
      - mongo-db