version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGODB_APPLICATION_DATABASE=scheduler-management-db
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/scheduler-management-db
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    #volumes:
    #  - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
    networks:
      - app-network
  app:
    build: .
    image: edilson/scheduler-management
    volumes:
      - .:/scheduler-management-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
